jobs:
- job: Directory_CICDCheck
  displayName: 'Validate Pull Request in Scratch org'
  timeoutInMinutes: 359
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: sfpwowerscript-installsfdx-task@9
    - task: sfpwowerscripts-analyzewithpmd-task@8
      inputs:
        format: html