jobs:
- job: Directory_CICDCheck
  displayName: 'Validate Pull Request in Scratch org'
  timeoutInMinutes: 359
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: sfpwowerscript-installsfdx-task@9
    - task: sfpwowerscript-authenticateorg-task@10
      inputs:
        method: 'Credentials'
        username: 'caitlyn.mills@accenture.com'
        password: '$(password)'
        securitytoken: '$(token)'
        alias: 'DevHub'
        isdevhub: true
    - task: sfpwowerscript-managescratchorg-task@9
      displayName: 'Create scratch org: scratchorg'
      inputs:
        action: 'Create'
        config_file_path: 'config/project-scratch-def.json'
        alias: 'aliasnametest'
        devhub_alias: 'DevHub'
        maintainorg: 'delete'
    - task: sfpowerscript-deploysourcetoorg-task@11
      displayName: 'Deploy metadata to org: scratchorg'
      inputs:
        target_org: 'aliasnametest'
        source_directory: 'force-app'
        checkonly: false
        wait_time: '20'
        testlevel: 'NoTestRun'
        isToBreakBuildIfEmpty: true
    - task: sfpwowerscript-validateapextestcoverage-task@5
      displayName: 'Verify code coverage of 75%'
      inputs:
        target_org: 'aliasnametest'
        test_coverage: '0'
    - task: sfpwowerscripts-analyzewithpmd-task@8
      inputs:
        directory: 
        ruleset: 'Custom'
        rulesetpath: 'pmd-ruleset.xml'