jobs:
- job: Directory_CICDCheck
  displayName: 'Validate Pull Request in Scratch org'
  timeoutInMinutes: 359
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: sfpwowerscript-installsfdx-task@7
      displayName: 'Install SalesforceDX'
    - task: sfpwowerscript-authenticateorg-task@9
      displayName: 'Authenticate against DevHub Org'
      inputs:
        method: 'ServiceConnection'
        salesforce_connection: 'DevHub'
        alias: 'DevHub'
    - task: sfpwowerscript-managescratchorg-task@8
      displayName: 'Create scratch org: scratchorg'
      inputs:
        action: 'Create'
        config_file_path: 'config/project-scratch-def.json'
        alias: 'scratchorg'
        devhub_alias: 'DevHub'
        maintainorg: 'delete'
    - task: sfpowerscript-deploysourcetoorg-task@10
      displayName: 'Deploy metadata to org: scratchorg'
      inputs:
        target_org: 'scratchorg'
        source_directory: 'force-app'
        checkonly: false
        wait_time: '20'
        testlevel: 'RunAllTestsInOrg'
        isToBreakBuildIfEmpty: true
    - task: sfpwowerscript-validateapextestcoverage-task@4
      displayName: 'Verify code coverage of 75%'
      inputs:
        target_org: 'scratchorg'
        test_coverage: '75'